project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "BSTA 511/611 Fall 2024"
  navbar:
    background: primary
    search: true
    logo: "images/IMG_7897_med.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      # - href: class_slides.qmd
      #   text: Slides
      # - href: weeks.qmd
      #   text: Weeks
      # - href: homework.qmd
      #   text: Homework
      # - href: homework_solutions.qmd
      #   text: Homework solutions
      # - href: about.qmd
      #   text: About
  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - href: instructors.qmd
        text: Instructors        
      - href: schedule.qmd
        text: Schedule
      # - href: class_slides.qmd
      #   text: Slides
      # - href: weeks.qmd
      #   text: Weeks
      # - href: homework.qmd
      #   text: Homework
      # - href: homework_solutions.qmd
      #   text: Homework solutions
            
format:
  html:
    theme:
      - sandstone
      - custom.scss
    css: styles.css
    toc: true


