---
title: "Week 7"
description: "Inference for difference in means, one proportion, and difference in proportions, and power"
date: "11/11/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Overview of Week 7

::::: grid
::: g-col-6
### Mon: Day 11

-   Inference for difference in means from two independent sample (2-sample t-test)
-   Power and sample size calculations
:::

::: g-col-6
### Wed: Day 12

-   Inference for proportions
    -   CIs vs. hypothesis tests
    -   One proportion from one sample
    -   Difference in proportions from two independent samples
:::
:::::

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| 11 | CI's for 1 mean: 4.2 | [Day 9: slides 1-12](../slides/Day09_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day11_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day09_bsta511_notes.pdf) | [Day 9 Part 1](https://echo360.org/lesson/49845aaf-0a16-40ee-ad8f-9a0eed89561f/classroom#sortDirection=desc) | 17 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day09_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day09_bsta511_code.qmd) |
|  | 4.2 con'td | [Day 9: slides 13-19](../slides/Day09_bsta511.qmd#/how-to-interpret-a-c-i-12) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd#how-to-interpret-a-c-i-12) | same | [Day 9 Part 2](https://echo360.org/lesson/0a8e8094-9093-4d7a-b627-d5b4093aa3d7/classroom#sortDirection=desc) | 17 min | same | same |
|  | 4.2 con'td, 5.1.1, 5.1.2 (pgs. 238-242) | [Day 9: slides 20-23](../slides/Day09_bsta511.qmd#/calculating-the-c-i-for-the-population-mean-using-s) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day09_bsta511_md.qmd#calculating-the-c-i-for-the-population-mean-using-s) | same | [Day 9 Part 3](https://echo360.org/lesson/c6a7b108-10ce-401c-b9e8-712388f4e852/classroom#sortDirection=desc) | 14 min | same | same |
| 12 | Hyp test 1 mean intro | [Day 10 Part 1: slides 1-13](../slides/Day10_part1_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day12_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day10_part1_bsta511_md.qmd) | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day10_part1_bsta511_notes.pdf) | [Day 10 Part 1](https://echo360.org/lesson/68afabcf-82d3-4de6-8bab-1ff39f1b18fd/classroom#sortDirection=desc) | 26 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day10_part1_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day10_part1_bsta511_code.qmd) |
|  | Hyp test steps: 4.3, 5.1 | [Day 10 Part 1: slides 14-25](../slides/Day10_part1_bsta511.qmd#/steps-in-a-hypothesis-test) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day10_part1_bsta511_md.qmd#steps-in-a-hypothesis-test) | same | [Day 10 Part 2](https://echo360.org/lesson/2ab2f4d3-9a1c-42ea-aee9-c19158171058/classroom#sortDirection=desc) | 36 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day10_part1_bsta511_code.qmd#steps-in-a-hypothesis-test) |
|  | R demo | [Day 10 Part 1: slides 26-34](../slides/Day10_part1_bsta511.qmd#/running-a-t-test-in-r) | same | [{{< iconify streamline web size=20px >}}](../slides_md/Day10_part1_bsta511_md.qmd#running-a-t-test-in-r) | same | [Day 10 Part 3](https://echo360.org/lesson/249fd75c-de00-451a-89c6-aa7b72ec56ab/classroom#sortDirection=desc) | 25 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day10_part1_bsta511_code.qmd#running-a-t-test-in-r) |
|  |  | [Day 10 Part 2](../slides/Day10_part2_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day10_part2_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day10_part2_bsta511_md.qmd) |  | No recording |  | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day10_part2_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day10_part2_bsta511_code.qmd) |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

## Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F24/tree/main/data)

-   Day 11: [CaffeineTaps.csv](/data/CaffeineTaps.csv)

## Class discussion

During class you will be working in groups discussing the following:

### Day 11

-   Book 5.26 a-b (HW includes part (c) as well)
-   R1: DDS expenditures by ethnicity
-   PSS1: Book 4.22 - Power & sample size T/F questions
-   PSS2: Power & sample size calculations

### Day 12

-   Book 8.2, 8.14, 8.24 (plus extra (d))
-   PSS1: Legalize Marijuana, Part III

## Homework

-   [HW 5](../homework/HW_5_F24_bsta511.qmd) covers Days 11 -12 and is due on Sat, 11/16
-   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for typos in book.
