---
title: "Week 4"
description: "Bayes' Rule & EDA"
date: "10/21/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Overview of Week 4

::::: grid
::: g-col-6
### Day 6

-   Random variables: Section 3.1
-   Binomial distribution: Section 3.2
:::

::: g-col-6
### Day 7

-   Normal distribution: Section 3.3
-   Poisson distribution: Section 3.4
:::
:::::

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|----|----|----|----|----|----|----|----|----|----|
| 6 | Random Variables (3.1.1-3.1.3) | [Day 6: slides 1-6](../slides/Day06_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../LaTeX_slides/Day06_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../LaTeX_slides/Day06_bsta511_notes.pdf) | [Day 6 Part 1](https://echo360.org/lesson/6b3df5b4-2997-43af-81b7-91da94b7100f/classroom#sortDirection=desc) | 24 min |  |  |
|  | Linear combinations of RV's (3.1.4) | [Day 6: slides 7-10](../slides/Day06_bsta511.qmd) | same |  | same | [Day 6 Part 2](https://echo360.org/lesson/a191ba39-ebb5-4421-8ee1-67348d3e6f57/classroom#sortDirection=desc) | 14 min |  |  |
|  | Binomial distribution (3.2) | [Day 6: slides 11-15](../slides/Day06_bsta511.qmd) | same |  | same | [Day 6 Part 3](https://echo360.org/lesson/907b2ae8-1572-44e8-a632-c64ed8fe67b3/classroom#sortDirection=desc) | 27 min |  |  |
| 7 | Normal distribution and calculatin probabilities for standard normal distribution (3.3.1, 3.3.3) | [Day 7: slides 1-5](../slides/Day07_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../LaTeX_slides/Day07_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../LaTeX_slides/Day07_bsta511_notes.pdf) | [Day 7 Part 1](https://echo360.org/lesson/6d845f5b-d50f-4aeb-af90-7eaded81ab99/classroom#sortDirection=desc) | 27 min |  |  |
|  | Calculating normal probabilities using z-scores (3.3.2, 3.3.4) | [Day 7: slides 6-7](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 2](https://echo360.org/lesson/c42e49bf-a852-403f-b13d-2f47cb36accf/classroom#sortDirection=desc) | 15 min |  |  |
|  | Normal approximation of the binomial distribution (3.3.6) | [Day 7: slides 8-9](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 3](https://echo360.org/lesson/7e84a51f-7d39-47fe-a27d-84974592ce65/classroom#sortDirection=desc) | 14 min |  |  |
|  | Poisson distribution (3.4) | [Day 7: slides 10-12](../slides/Day07_bsta511.qmd) | same |  | same | [Day 7 Part 4](https://echo360.org/lesson/cf2c19ad-62b5-44b5-ac0a-f85a32f0e599/classroom#sortDirection=desc) | 15 min |  |  |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

## Class discussion

During class you will be working in groups discussing the following:

### Day04

-   coming soon!

### Day05

-   coming soon!

## Homework - coming soon!

<!-- -   [HW 3](../homework/HW_3_F24_bsta511.qmd) due on Sat, 10/26 -->
